FROM python

WORKDIR /prob

COPY . ./

RUN apt-get update && apt-get install -yq \
    python-smbus && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Install i2c-tools (i2c comm)
RUN apt-get install i2c-tools

# Install dependencies
RUN pip install -r requirements.txt

COPY . /prob

CMD ["python", "./src/main.py"]